### ISSUE TITLE
a feature idea: encourage/support the usage of stefil asserts outside the unit tests

### ISSUE THREAD

**Issue by attila-lendvai** [luismbo/stefil#10]
maybe it would be worth a few thoughts to consider supporting/encouraging the usage of stefil's asserts in the project code itself (as opposed to only in its unit tests).

e.g. when the asserts in the project code are run without a dynamic test environment, then stefil asserts can behave differently in case of a failed assertion. currently they print stuff to stderr and signal an error, which is not too bad, but to be honest i've never considered thoroughly this use-case, nor have i used stefil asserts outside of the unit tests.

the current behavior was implemented with REPL usage in mind, mostly to enable copy-pasting parts of the test code to the REPL without any hassle.

**Comment by luismbo** [comment]
Indeed, this is an interesting idea. When such an IS assertion fails within a test run, it'd be collected with a nicer explanation than plain assert.
