### ISSUE TITLE
Stefil failing to load in (ql:quickload :stefil)

### ISSUE THREAD

**Issue by ghost** [luismbo/stefil#11]
Hi luismbo,

When I attempt to (ql:quickload :stefil) I receive the following error:

http://paste.lisp.org/display/144037

This is using the latest version of slime (not sure if it is related or not).

So far I cannot reproduce this failure with any other packages at the moment.

**Comment by luismbo** [comment]
It might be related to recent changes in SLIME, yes. Do you use Stefil's SLIME integration?

**Comment by ghost** [comment]
I haven't yet.  Just started with stefil today,  also updated slime today as well.  Using slime git repo.

<div>-------- Original message --------</div><div>From: Luís Oliveira notifications@github.com </div><div>Date:10/14/2014  5:00 PM  (GMT-05:00) </div><div>To: luismbo/stefil stefil@noreply.github.com </div><div>Cc: Matthew Carter m@ahungry.com </div><div>Subject: Re: [stefil] Stefil failing to load in (ql:quickload :stefil) (#11) </div><div>
</div>It might be related to recent changes in SLIME, yes. Do you use Stefil's SLIME integration?

**Comment by ghost** [comment]
Closing issue, problem occurs as a result of quickloading :swank package (which stefil simply depends on in asd file).

**Comment by luismbo** [comment]
Cool, thanks for digging further.
